# Generated by Django 6.0.6 on 2026-06-14 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='股票代码')),
                ('name', models.CharField(max_length=50, verbose_name='股票名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否监控中')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '关注股票',
                'verbose_name_plural': '关注股票',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='MinuteBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='分钟时间戳')),
                ('open', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='开盘价')),
                ('close', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='收盘价')),
                ('high', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='最高价')),
                ('low', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='最低价')),
                ('volume', models.BigIntegerField(verbose_name='成交量')),
                ('turnover', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='成交额')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minute_bars', to='stocks.stock', verbose_name='股票')),
            ],
            options={
                'verbose_name': '分钟K线',
                'verbose_name_plural': '分钟K线',
                'ordering': ['datetime'],
                'unique_together': {('stock', 'datetime')},
            },
        ),
        migrations.CreateModel(
            name='DailyQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField(verbose_name='交易日期')),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='开盘价')),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='收盘价')),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='最高价')),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='最低价')),
                ('high_time', models.DateTimeField(blank=True, null=True, verbose_name='最高点时间')),
                ('low_time', models.DateTimeField(blank=True, null=True, verbose_name='最低点时间')),
                ('open_close_diff', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='收盘-开盘差值')),
                ('open_close_pct', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='收盘-开盘百分比')),
                ('high_low_diff', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='最高-最低差值')),
                ('high_low_pct', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='最高-最低百分比')),
                ('volume', models.BigIntegerField(blank=True, null=True, verbose_name='成交量')),
                ('turnover', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='成交额')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_quotes', to='stocks.stock', verbose_name='股票')),
            ],
            options={
                'verbose_name': '每日行情',
                'verbose_name_plural': '每日行情',
                'ordering': ['-trade_date'],
                'unique_together': {('stock', 'trade_date')},
            },
        ),
    ]
