# Generated by Django 6.0.6 on 2026-06-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='股票名称'),
        ),
    ]
