# Generated by Django 6.0.6 on 2026-06-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_alter_stock_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyquote',
            name='change_diff',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='涨跌额'),
        ),
        migrations.AddField(
            model_name='dailyquote',
            name='change_pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='涨跌幅'),
        ),
        migrations.AddField(
            model_name='dailyquote',
            name='prev_close',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='昨收价'),
        ),
    ]
