# Generated by Django 6.0.6 on 2026-09-04 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_dailyquote_change_diff_dailyquote_change_pct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('base_url', models.CharField(help_text='OpenAI 兼容 base_url，如 https://api.deepseek.com', max_length=200, verbose_name='接口地址')),
                ('api_key_encrypted', models.TextField(verbose_name='加密的 API Key')),
                ('model', models.CharField(max_length=100, verbose_name='模型名')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AI 服务商',
                'verbose_name_plural': 'AI 服务商',
                'ordering': ['-is_enabled', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AiCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('analysis', '个股分析'), ('screener_translate', '选股条件翻译'), ('screener_comment', '选股结果点评')], max_length=30, verbose_name='用途')),
                ('success', models.BooleanField(default=True, verbose_name='成功')),
                ('prompt_tokens', models.IntegerField(blank=True, null=True, verbose_name='输入 tokens')),
                ('completion_tokens', models.IntegerField(blank=True, null=True, verbose_name='输出 tokens')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.stock', verbose_name='股票')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.aiprovider', verbose_name='服务商')),
            ],
            options={
                'verbose_name': 'AI 调用记录',
                'verbose_name_plural': 'AI 调用记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
