# Generated by Django 6.0.6 on 2026-09-05 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_aiprovider_aicalllog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenerPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='预设名称')),
                ('spec', models.JSONField(verbose_name='筛选条件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '选股预设',
                'verbose_name_plural': '选股预设',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='stock',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='成本价'),
        ),
        migrations.AddField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='持股数(股)'),
        ),
        migrations.CreateModel(
            name='MarketDailySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('industry_ff', '行业资金流'), ('concept_ff', '概念资金流'), ('etf_share', 'ETF份额')], max_length=30, verbose_name='快照类型')),
                ('trade_date', models.DateField(verbose_name='交易日期')),
                ('payload', models.JSONField(verbose_name='快照数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '市场日度快照',
                'verbose_name_plural': '市场日度快照',
                'ordering': ['-trade_date'],
                'unique_together': {('kind', 'trade_date')},
            },
        ),
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('price_above', '价格上穿'), ('price_below', '价格下穿'), ('daily_pct_above', '日涨幅达到'), ('daily_pct_below', '日跌幅达到')], max_length=30, verbose_name='规则类型')),
                ('threshold', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='阈值')),
                ('note', models.CharField(blank=True, default='', max_length=100, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True, verbose_name='最近触发时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='stocks.stock', verbose_name='股票')),
            ],
            options={
                'verbose_name': '价格提醒',
                'verbose_name_plural': '价格提醒',
                'ordering': ['stock__code', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200, verbose_name='提醒内容')),
                ('trade_date', models.DateField(verbose_name='触发交易日')),
                ('is_read', models.BooleanField(default=False, verbose_name='已读')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='触发时间')),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.stock', verbose_name='股票')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='stocks.pricealert', verbose_name='提醒规则')),
            ],
            options={
                'verbose_name': '提醒记录',
                'verbose_name_plural': '提醒记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
