# Generated by Django 6.0.6 on 2026-09-05 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_screenerpreset_stock_cost_price_stock_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分组名称')),
                ('order', models.IntegerField(default=0, verbose_name='显示顺序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '自选分组',
                'verbose_name_plural': '自选分组',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='stock',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks', to='stocks.stockgroup', verbose_name='分组'),
        ),
    ]
