# Generated by Django 6.0.6 on 2026-09-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_stockgroup_stock_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketdailysnapshot',
            name='kind',
            field=models.CharField(choices=[('industry_ff', '行业资金流'), ('concept_ff', '概念资金流'), ('etf_share', 'ETF份额'), ('market_ff', '大盘主力资金流')], max_length=30, verbose_name='快照类型'),
        ),
    ]
