# Generated by Django 6.0.6 on 2026-09-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_alter_marketdailysnapshot_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectorDimConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40, unique=True, verbose_name='维度标识')),
                ('name', models.CharField(max_length=50, verbose_name='维度名称')),
                ('weight', models.FloatField(default=1.0, verbose_name='权重')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='维度参数（窗口/阈值等）')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('disabled_reason', models.CharField(blank=True, default='', max_length=200, verbose_name='停用原因')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '探测器维度配置',
                'verbose_name_plural': '探测器维度配置',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='DetectorRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField(unique=True, verbose_name='扫描交易日')),
                ('status', models.CharField(default='ok', max_length=20, verbose_name='运行状态')),
                ('targets_scanned', models.IntegerField(default=0, verbose_name='扫描对象数')),
                ('calm_count', models.IntegerField(default=0, verbose_name='平静对象数')),
                ('signals_new', models.IntegerField(default=0, verbose_name='新增观察信号数(周期1)')),
                ('signals_sustained', models.IntegerField(default=0, verbose_name='维持信号数(周期≥2)')),
                ('reviewed_count', models.IntegerField(default=0, verbose_name='回看信号数')),
                ('hit_count', models.IntegerField(default=0, verbose_name='回看命中数')),
                ('hit_rate', models.FloatField(blank=True, null=True, verbose_name='回看命中率')),
                ('degraded', models.JSONField(blank=True, default=list, verbose_name='降级记录')),
                ('adjustments', models.JSONField(blank=True, default=list, verbose_name='权重/阈值调整流水')),
                ('matrix', models.JSONField(blank=True, default=dict, verbose_name='板块微变矩阵')),
                ('message', models.CharField(blank=True, default='', max_length=300, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '探测器扫描记录',
                'verbose_name_plural': '探测器扫描记录',
                'ordering': ['-trade_date'],
            },
        ),
        migrations.AlterField(
            model_name='marketdailysnapshot',
            name='kind',
            field=models.CharField(choices=[('industry_ff', '行业资金流'), ('concept_ff', '概念资金流'), ('etf_share', 'ETF份额'), ('market_ff', '大盘主力资金流'), ('margin', '融资余额')], max_length=30, verbose_name='快照类型'),
        ),
        migrations.CreateModel(
            name='DetectorSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_kind', models.CharField(choices=[('index', '指数'), ('stock', '自选股'), ('industry', '行业板块'), ('concept', '概念板块')], max_length=20, verbose_name='对象类型')),
                ('target_code', models.CharField(max_length=30, verbose_name='对象代码')),
                ('target_name', models.CharField(blank=True, default='', max_length=50, verbose_name='对象名称')),
                ('trade_date', models.DateField(verbose_name='信号交易日')),
                ('direction', models.CharField(choices=[('up', '向上微变'), ('down', '向下微变')], max_length=10, verbose_name='方向')),
                ('cycles', models.IntegerField(default=1, verbose_name='连续周期数')),
                ('score', models.FloatField(default=0.0, verbose_name='同向强度(0-100)')),
                ('severity', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='low', max_length=10, verbose_name='严重程度')),
                ('status', models.CharField(choices=[('watching', '观察中'), ('active', '维持中'), ('confirmed', '已兑现'), ('missed', '未兑现')], default='watching', max_length=20, verbose_name='状态')),
                ('dimensions', models.JSONField(blank=True, default=dict, verbose_name='维度明细')),
                ('review_hit', models.BooleanField(blank=True, null=True, verbose_name='回看是否兑现')),
                ('hit_date', models.DateField(blank=True, null=True, verbose_name='兑现日期')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='回看时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '探测器信号',
                'verbose_name_plural': '探测器信号',
                'ordering': ['-trade_date', '-score'],
                'indexes': [models.Index(fields=['trade_date', 'severity'], name='stocks_dete_trade_d_7c4200_idx'), models.Index(fields=['status', 'review_hit'], name='stocks_dete_status_b6ef9e_idx')],
                'unique_together': {('target_kind', 'target_code', 'trade_date')},
            },
        ),
    ]
